# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  couchdbB1:
    container_name: couchdbB1
    image: hyperledger/fabric-couchdb
    ports:
      - "5984:5984"

  peer0.B1.example.com:
    container_name: peer0.B1.example.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.B1.example.com
      - CORE_PEER_ADDRESS=peer0.B1.example.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.B1.example.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.B1.example.com:7051
      - CORE_PEER_LOCALMSPID=B1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbB1:5984
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/B1.example.com/peers/peer0.B1.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/B1.example.com/peers/peer0.B1.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    depends_on:
      - couchdbB1
    extra_hosts:
     - "orderer.example.com:10.174.13.185"

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.B1.example.com:7051
      - CORE_PEER_LOCALMSPID=B1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/B1.example.com/peers/peer0.B1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/B1.example.com/peers/peer0.B1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/B1.example.com/peers/peer0.B1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/B1.example.com/users/Admin@B1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.B1.example.com
    extra_hosts:
     - "orderer.example.com:10.174.13.185"
     - "peer0.B1.example.com:10.51.120.220"
     - "peer0.B2.example.com:10.51.126.19"
     - "peer0.B3.example.com:10.51.116.133"
     - "peer0.C1.example.com:10.51.126.5"
