# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com

#  mysql:
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: Goodluck7
#    container_name: mysql
#    volumes:
#      - /home/fabric/mysqlData:/var/lib/mysql
#    ports:
#      - 3306:3306
